### PR TITLE
Context parsers

### PR DESCRIPTION
**Pull request by slyles1001**
Hello,
a teammate and I wrote some code to extract thread context from minidump files. Please review and reach out if you have critiques or ideas for improvement!

Seth

### CODE REVIEW

**Comment by skelsec** [comment]
Hello,
This is the largest (by effort) PR I have ever received, thank you very much.
The only problem I see is: there is some functionality implemented in the `ContextStream.py` file which requires `multiprocessing` and `numpy`. Could it be possible to either move the imports to the `main` function (to hide them) or to create a separate script for this parsing functionality which we can store in the `utils` folder?
Problem is that this functionality is not an integral part for the context parsing and thus would require all users to install huge packages (numpy) and include multiprocessing which is not always available (webassembly/other exotics)
Please let me know if you wish to do it yourself or I can just accept the PR as-is and do it myself.
Awesome work, I'm really grateful.

Best Regards,
SkelSec

**Comment by slyles1001** [comment]
Hey, I think that was an old commit; in the most recent (files changed) those packages are removed. I'll squash the commits and update, should get rid of it!

**Comment by slyles1001** [comment]
changed git history so I'll open a new request

**Comment by slyles1001** [comment]
ok, squashed to 2 commits, `subprocessing` and `numpy` should be gone (or buried) from history now

**Comment by skelsec** [comment]
You are awesome, thank you very much!
hit me up on twitter if you want a shoutout

**Pull request merged**
